apiVersion: v1
kind: Service
metadata:
  name: sfc-team
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-team
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Internal ClusterIP service for Team component in SFC application"
spec:
  selector:
    app.kubernetes.io/name: sfc-team
  type: ClusterIP
  ports:
    - name: sfc-team-cluster-service-http-port
      protocol: TCP
      port: 7565
      targetPort: 7565
    - name: sfc-team-cluster-service-https-port
      protocol: TCP
      port: 7566
      targetPort: 7566
  internalTrafficPolicy: Cluster