apiVersion: v2
name: sfc-team
description: "SFC Team component in SFC application"
keywords:
  - Street Football Club
  - Application
  - Team
type: application
version: 1.0.0
appVersion: "0.0.0"
dependencies:
  - name: sfc-common
    version: 1.0.0
    repository: "file://../../../Bff/sfc-bff/helm/charts/common"
  - name: sfc-redis
    version: 1.0.0
    repository: "file://../../../Bff/sfc-bff/helm/charts/redis"
  - name: sfc-mssql
    version: 1.0.0
    repository: "file://../../../Bff/sfc-bff/helm/charts/mssql"
  - name: sfc-rabbitmq
    version: 1.0.0
    repository: "file://../../../Bff/sfc-bff/helm/charts/rabbitmq"
  - name: sfc-identity
    version: 1.0.0
    repository: "file://../../sfc-identity-service/helm"
  - name: sfc-player
    version: 1.0.0
    repository: "file://../../sfc-player-service/helm"