#github action to build and test SFC.Team application

name: Build and Test SFC.Team Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Install Redis
          run: sudo apt-get install -y redis-tools redis-server

        - name: Verify Redis
          run: redis-cli ping

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release --no-restore

        - name: Test
          run: dotnet test --no-build --verbosity normal
